# Seed everything (LightningCLI handles this when set here)
# seed_everything: 42

# ----------------------------
# Model hyperparameters
# ----------------------------
model:
  in_channels: 1            # set to 3 for RGB datasets later
  out_channels: 1
  z_dim: 32
  num_classes: 10
  cond_dim: 16
  use_film: false

  # Optimization + loss schedule
  lr: 3.0e-4
  weight_decay: 1.0e-4
  beta: 0.25
  kl_warmup_epochs: 50
  max_epochs: 100

# ----------------------------
# Data settings
# ----------------------------
data:
  data_dir: ./data
  batch_size: 128
  num_workers: 8
  val_split: 5000
  image_channels: 1         # keep in sync with model.{in,out}_channels
  num_classes: 10
  predict_samples_per_class: 8
  pin_memory: true
  persistent_workers: true

# ----------------------------
# Trainer configuration
# ----------------------------
trainer:
  default_root_dir: runs
  accelerator: auto
  devices: auto
  max_epochs: 100
  precision: 32-true
  log_every_n_steps: 50
  gradient_clip_val: 1.0
  deterministic: false
  enable_checkpointing: true
  default_root_dir: ./runs

