seed_everything: 42

# ----------------------------
# Model hyperparameters
# ----------------------------
model:
  in_channels: 1
  out_channels: 1
  z_dim: 32
  num_classes: 10
  cond_dim: 16
  use_film: false

  # Optimization + loss schedule
  lr: 0.002
  weight_decay: 0.0001
  beta: 6.0                 # total correlation target weight (Î² in the paper)
  kl_warmup_epochs: 10
  max_epochs: 50
  loss:
    name: beta_tc
    mutual_information_weight: 1.0
    total_correlation_weight: 1.0
    dimension_wise_kl_weight: 1.0
    anneal_target: tc         # apply warm-up to the TC weight

# ----------------------------
# Data settings
# ----------------------------
data:
  data_dir: ./data
  batch_size: 128
  num_workers: 8
  val_split: 5000
  image_channels: 1
  num_classes: 10
  predict_samples_per_class: 8
  pin_memory: true
  persistent_workers: true

# ----------------------------
# Trainer configuration
# ----------------------------
trainer:
  default_root_dir: runs
  accelerator: auto
  devices: auto
  max_epochs: 50
  precision: 32-true
  log_every_n_steps: 50
  gradient_clip_val: 1.0
  deterministic: false
  enable_checkpointing: true
  default_root_dir: ./runs

